- hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - tags: [ always ]
      loop: ["common.yml","{{ env }}/environment.yml"]
      ansible.builtin.include_vars: "{{ item }}"
  tasks:
    - tags: [ never, create, delete ]
      block:
        - name: Get VPC info
          register: reg_vpc
          amazon.aws.ec2_vpc_net_info:
            profile: "{{ profile|default(omit) }}"
            region: "{{ region }}"
            filters: {"tag:Name": "default"}
        - name: Get VPC ID
          ansible.builtin.set_fact:
            vpc_id: "{{ reg_vpc.vpcs[0].vpc_id }}"

    - tags: [ never, create ]
      block:
        - name: Create Route 53 zone
          community.aws.route53_zone:
            profile: "{{ profile|default(omit) }}"
            zone: "{{ private_domain }}"
            state: present
            vpc_id: "{{ vpc_id }}"
            vpc_region: "{{ region }}"

    - tags: [ never, delete ]
      block:
        - name: Show Route 53 zone to delete
          ansible.builtin.debug:
            msg: "{{ private_domain }}"
        - name: Confirm to continue
          when: noprompt is not defined
          ansible.builtin.pause:
            prompt: "Press Enter to continue. Press CTRL+C => A to abort."
        - name: Delete Route 53 zone
          community.aws.route53_zone:
            profile: "{{ profile|default(omit) }}"
            zone: "{{ private_domain }}"
            state: absent
            vpc_id: "{{ vpc_id }}"
            vpc_region: "{{ region }}"
